/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_CellsToAddMod_H_
#define	_CellsToAddMod_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_SEQUENCE.h>

#include "PhysCellId.h"
#include "Q-OffsetRangeList.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CellsToAddMod */
typedef struct CellsToAddMod {
	PhysCellId_t	 physCellId;
	Q_OffsetRangeList_t	 cellIndividualOffset;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellsToAddMod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellsToAddMod;
extern asn_SEQUENCE_specifics_t asn_SPC_CellsToAddMod_specs_1;
extern asn_TYPE_member_t asn_MBR_CellsToAddMod_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CellsToAddMod_H_ */
#include <skeletons/asn_internal.h>
