/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_CSI_AssociatedReportConfigInfo_H_
#define	_CSI_AssociatedReportConfigInfo_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/NativeInteger.h>
#include <skeletons/asn_SEQUENCE_OF.h>
#include <skeletons/constr_CHOICE.h>
#include <skeletons/constr_SEQUENCE.h>
#include <skeletons/constr_SEQUENCE_OF.h>

#include "CSI-ReportConfigId.h"
#include "TCI-StateId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CSI_AssociatedReportConfigInfo__resourcesForChannel_PR {
	CSI_AssociatedReportConfigInfo__resourcesForChannel_PR_NOTHING,	/* No components present */
	CSI_AssociatedReportConfigInfo__resourcesForChannel_PR_nzp_CSI_RS,
	CSI_AssociatedReportConfigInfo__resourcesForChannel_PR_csi_SSB_ResourceSet
} CSI_AssociatedReportConfigInfo__resourcesForChannel_PR;

/* CSI-AssociatedReportConfigInfo */
typedef struct CSI_AssociatedReportConfigInfo {
	CSI_ReportConfigId_t	 reportConfigId;
	struct CSI_AssociatedReportConfigInfo__resourcesForChannel {
		CSI_AssociatedReportConfigInfo__resourcesForChannel_PR present;
		union CSI_AssociatedReportConfigInfo__resourcesForChannel_u {
			struct CSI_AssociatedReportConfigInfo__resourcesForChannel__nzp_CSI_RS {
				long	 resourceSet;
				struct CSI_AssociatedReportConfigInfo__resourcesForChannel__nzp_CSI_RS__qcl_info {
					A_SEQUENCE_OF(TCI_StateId_t) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *qcl_info;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *nzp_CSI_RS;
			long	 csi_SSB_ResourceSet;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} resourcesForChannel;
	long	*csi_IM_ResourcesForInterference;	/* OPTIONAL */
	long	*nzp_CSI_RS_ResourcesForInterference;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSI_AssociatedReportConfigInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSI_AssociatedReportConfigInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_CSI_AssociatedReportConfigInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_CSI_AssociatedReportConfigInfo_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _CSI_AssociatedReportConfigInfo_H_ */
#include <skeletons/asn_internal.h>
