/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_DRB_ToAddMod_H_
#define	_DRB_ToAddMod_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/NativeEnumerated.h>
#include <skeletons/NativeInteger.h>
#include <skeletons/constr_CHOICE.h>
#include <skeletons/constr_SEQUENCE.h>

#include "DRB-Identity.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DRB_ToAddMod__cnAssociation_PR {
	DRB_ToAddMod__cnAssociation_PR_NOTHING,	/* No components present */
	DRB_ToAddMod__cnAssociation_PR_eps_BearerIdentity,
	DRB_ToAddMod__cnAssociation_PR_sdap_Config
} DRB_ToAddMod__cnAssociation_PR;
typedef enum DRB_ToAddMod__reestablishPDCP {
	DRB_ToAddMod__reestablishPDCP_true	= 0
} e_DRB_ToAddMod__reestablishPDCP;
typedef enum DRB_ToAddMod__recoverPDCP {
	DRB_ToAddMod__recoverPDCP_true	= 0
} e_DRB_ToAddMod__recoverPDCP;

/* Forward declarations */
struct PDCP_Config;
struct SDAP_Config;

/* DRB-ToAddMod */
typedef struct DRB_ToAddMod {
	struct DRB_ToAddMod__cnAssociation {
		DRB_ToAddMod__cnAssociation_PR present;
		union DRB_ToAddMod__cnAssociation_u {
			long	 eps_BearerIdentity;
			struct SDAP_Config	*sdap_Config;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *cnAssociation;
	DRB_Identity_t	 drb_Identity;
	long	*reestablishPDCP;	/* OPTIONAL */
	long	*recoverPDCP;	/* OPTIONAL */
	struct PDCP_Config	*pdcp_Config;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRB_ToAddMod_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_reestablishPDCP_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_recoverPDCP_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DRB_ToAddMod;
extern asn_SEQUENCE_specifics_t asn_SPC_DRB_ToAddMod_specs_1;
extern asn_TYPE_member_t asn_MBR_DRB_ToAddMod_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDCP-Config.h"
#include "SDAP-Config.h"

#endif	/* _DRB_ToAddMod_H_ */
#include <skeletons/asn_internal.h>
