/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -fcompound-names -findirect-choice -gen-PER -pdu=all -no-gen-example -no-gen-OER -fincludes-quoted -funnamed-unions -D nr-rrc-f60`
 */

#ifndef	_FeatureSetDownlinkId_H_
#define	_FeatureSetDownlinkId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FeatureSetDownlinkId */
typedef long	 FeatureSetDownlinkId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FeatureSetDownlinkId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FeatureSetDownlinkId;
asn_struct_free_f FeatureSetDownlinkId_free;
asn_struct_print_f FeatureSetDownlinkId_print;
asn_constr_check_f FeatureSetDownlinkId_constraint;
ber_type_decoder_f FeatureSetDownlinkId_decode_ber;
der_type_encoder_f FeatureSetDownlinkId_encode_der;
xer_type_decoder_f FeatureSetDownlinkId_decode_xer;
xer_type_encoder_f FeatureSetDownlinkId_encode_xer;
per_type_decoder_f FeatureSetDownlinkId_decode_uper;
per_type_encoder_f FeatureSetDownlinkId_encode_uper;
per_type_decoder_f FeatureSetDownlinkId_decode_aper;
per_type_encoder_f FeatureSetDownlinkId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FeatureSetDownlinkId_H_ */
#include "asn_internal.h"
