/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_FrequencyInfoDL_SIB_H_
#define	_FrequencyInfoDL_SIB_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/NativeInteger.h>
#include <skeletons/asn_SEQUENCE_OF.h>
#include <skeletons/constr_SEQUENCE.h>
#include <skeletons/constr_SEQUENCE_OF.h>

#include "MultiFrequencyBandListNR-SIB.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SCS_SpecificCarrier;

/* FrequencyInfoDL-SIB */
typedef struct FrequencyInfoDL_SIB {
	MultiFrequencyBandListNR_SIB_t	 frequencyBandList;
	long	 offsetToPointA;
	struct FrequencyInfoDL_SIB__scs_SpecificCarrierList {
		A_SEQUENCE_OF(struct SCS_SpecificCarrier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} scs_SpecificCarrierList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FrequencyInfoDL_SIB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FrequencyInfoDL_SIB;
extern asn_SEQUENCE_specifics_t asn_SPC_FrequencyInfoDL_SIB_specs_1;
extern asn_TYPE_member_t asn_MBR_FrequencyInfoDL_SIB_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SCS-SpecificCarrier.h"

#endif	/* _FrequencyInfoDL_SIB_H_ */
#include <skeletons/asn_internal.h>
