/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_MeasResultSFTD_EUTRA_H_
#define	_MeasResultSFTD_EUTRA_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/NativeInteger.h>
#include <skeletons/constr_SEQUENCE.h>

#include "EUTRA-PhysCellId.h"
#include "RSRP-Range.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MeasResultSFTD-EUTRA */
typedef struct MeasResultSFTD_EUTRA {
	EUTRA_PhysCellId_t	 eutra_PhysCellId;
	long	 sfn_OffsetResult;
	long	 frameBoundaryOffsetResult;
	RSRP_Range_t	*rsrp_Result;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResultSFTD_EUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResultSFTD_EUTRA;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasResultSFTD_EUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResultSFTD_EUTRA_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasResultSFTD_EUTRA_H_ */
#include <skeletons/asn_internal.h>
