/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_MeasQuantityResultsEUTRA_H_
#define	_MeasQuantityResultsEUTRA_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_SEQUENCE.h>

#include "RSRP-RangeEUTRA.h"
#include "RSRQ-RangeEUTRA.h"
#include "SINR-RangeEUTRA.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MeasQuantityResultsEUTRA */
typedef struct MeasQuantityResultsEUTRA {
	RSRP_RangeEUTRA_t	*rsrp;	/* OPTIONAL */
	RSRQ_RangeEUTRA_t	*rsrq;	/* OPTIONAL */
	SINR_RangeEUTRA_t	*sinr;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasQuantityResultsEUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasQuantityResultsEUTRA;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasQuantityResultsEUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasQuantityResultsEUTRA_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasQuantityResultsEUTRA_H_ */
#include <skeletons/asn_internal.h>
