/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_MeasResult2NR_H_
#define	_MeasResult2NR_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_SEQUENCE.h>

#include "ARFCN-ValueNR.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultNR;
struct MeasResultListNR;

/* MeasResult2NR */
typedef struct MeasResult2NR {
	ARFCN_ValueNR_t	*ssbFrequency;	/* OPTIONAL */
	ARFCN_ValueNR_t	*refFreqCSI_RS;	/* OPTIONAL */
	struct MeasResultNR	*measResultServingCell;	/* OPTIONAL */
	struct MeasResultListNR	*measResultNeighCellListNR;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResult2NR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResult2NR;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasResult2NR_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResult2NR_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasResultNR.h"
#include "MeasResultListNR.h"

#endif	/* _MeasResult2NR_H_ */
#include <skeletons/asn_internal.h>
