/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_MobilityFromNRCommand_H_
#define	_MobilityFromNRCommand_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_CHOICE.h>
#include <skeletons/constr_SEQUENCE.h>

#include "RRC-TransactionIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MobilityFromNRCommand__criticalExtensions_PR {
	MobilityFromNRCommand__criticalExtensions_PR_NOTHING,	/* No components present */
	MobilityFromNRCommand__criticalExtensions_PR_mobilityFromNRCommand,
	MobilityFromNRCommand__criticalExtensions_PR_criticalExtensionsFuture
} MobilityFromNRCommand__criticalExtensions_PR;

/* Forward declarations */
struct MobilityFromNRCommand_IEs;

/* MobilityFromNRCommand */
typedef struct MobilityFromNRCommand {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct MobilityFromNRCommand__criticalExtensions {
		MobilityFromNRCommand__criticalExtensions_PR present;
		union MobilityFromNRCommand__criticalExtensions_u {
			struct MobilityFromNRCommand_IEs	*mobilityFromNRCommand;
			struct MobilityFromNRCommand__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MobilityFromNRCommand_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MobilityFromNRCommand;
extern asn_SEQUENCE_specifics_t asn_SPC_MobilityFromNRCommand_specs_1;
extern asn_TYPE_member_t asn_MBR_MobilityFromNRCommand_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MobilityFromNRCommand-IEs.h"

#endif	/* _MobilityFromNRCommand_H_ */
#include <skeletons/asn_internal.h>
