/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_P0_PUCCH_H_
#define	_P0_PUCCH_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/NativeInteger.h>
#include <skeletons/constr_SEQUENCE.h>

#include "P0-PUCCH-Id.h"

#ifdef __cplusplus
extern "C" {
#endif

/* P0-PUCCH */
typedef struct P0_PUCCH {
	P0_PUCCH_Id_t	 p0_PUCCH_Id;
	long	 p0_PUCCH_Value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} P0_PUCCH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_P0_PUCCH;
extern asn_SEQUENCE_specifics_t asn_SPC_P0_PUCCH_specs_1;
extern asn_TYPE_member_t asn_MBR_P0_PUCCH_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _P0_PUCCH_H_ */
#include <skeletons/asn_internal.h>
