/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_PagingRecord_H_
#define	_PagingRecord_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/NativeEnumerated.h>
#include <skeletons/constr_SEQUENCE.h>

#include "PagingUE-Identity.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PagingRecord__accessType {
	PagingRecord__accessType_non3GPP	= 0
} e_PagingRecord__accessType;

/* PagingRecord */
typedef struct PagingRecord {
	PagingUE_Identity_t	 ue_Identity;
	long	*accessType;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PagingRecord_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_accessType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PagingRecord;
extern asn_SEQUENCE_specifics_t asn_SPC_PagingRecord_specs_1;
extern asn_TYPE_member_t asn_MBR_PagingRecord_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PagingRecord_H_ */
#include <skeletons/asn_internal.h>
