/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_PDSCH_ServingCellConfig_H_
#define	_PDSCH_ServingCellConfig_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/BOOLEAN.h>
#include <skeletons/NativeEnumerated.h>
#include <skeletons/NativeInteger.h>
#include <skeletons/constr_SEQUENCE.h>

#include "ServCellIndex.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDSCH_ServingCellConfig__xOverhead {
	PDSCH_ServingCellConfig__xOverhead_xOh6	= 0,
	PDSCH_ServingCellConfig__xOverhead_xOh12	= 1,
	PDSCH_ServingCellConfig__xOverhead_xOh18	= 2
} e_PDSCH_ServingCellConfig__xOverhead;
typedef enum PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH {
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n2	= 0,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n4	= 1,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n6	= 2,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n10	= 3,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n12	= 4,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n16	= 5
} e_PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH;

/* Forward declarations */
struct SetupRelease_PDSCH_CodeBlockGroupTransmission;

/* PDSCH-ServingCellConfig */
typedef struct PDSCH_ServingCellConfig {
	struct SetupRelease_PDSCH_CodeBlockGroupTransmission	*codeBlockGroupTransmission;	/* OPTIONAL */
	long	*xOverhead;	/* OPTIONAL */
	long	*nrofHARQ_ProcessesForPDSCH;	/* OPTIONAL */
	ServCellIndex_t	*pucch_Cell;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct PDSCH_ServingCellConfig__ext1 {
		long	*maxMIMO_Layers;	/* OPTIONAL */
		BOOLEAN_t	*processingType2Enabled;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDSCH_ServingCellConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_xOverhead_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_nrofHARQ_ProcessesForPDSCH_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PDSCH_ServingCellConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_PDSCH_ServingCellConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_PDSCH_ServingCellConfig_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetupRelease.h"

#endif	/* _PDSCH_ServingCellConfig_H_ */
#include <skeletons/asn_internal.h>
