/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_PTRS_DownlinkConfig_H_
#define	_PTRS_DownlinkConfig_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/NativeEnumerated.h>
#include <skeletons/NativeInteger.h>
#include <skeletons/asn_SEQUENCE_OF.h>
#include <skeletons/constr_SEQUENCE.h>
#include <skeletons/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PTRS_DownlinkConfig__resourceElementOffset {
	PTRS_DownlinkConfig__resourceElementOffset_offset01	= 0,
	PTRS_DownlinkConfig__resourceElementOffset_offset10	= 1,
	PTRS_DownlinkConfig__resourceElementOffset_offset11	= 2
} e_PTRS_DownlinkConfig__resourceElementOffset;

/* PTRS-DownlinkConfig */
typedef struct PTRS_DownlinkConfig {
	struct PTRS_DownlinkConfig__frequencyDensity {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *frequencyDensity;
	struct PTRS_DownlinkConfig__timeDensity {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *timeDensity;
	long	*epre_Ratio;	/* OPTIONAL */
	long	*resourceElementOffset;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PTRS_DownlinkConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_resourceElementOffset_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PTRS_DownlinkConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_PTRS_DownlinkConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_PTRS_DownlinkConfig_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _PTRS_DownlinkConfig_H_ */
#include <skeletons/asn_internal.h>
