/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_ReportSFTD_NR_H_
#define	_ReportSFTD_NR_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/BOOLEAN.h>
#include <skeletons/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportSFTD-NR */
typedef struct ReportSFTD_NR {
	BOOLEAN_t	 reportSFTD_Meas;
	BOOLEAN_t	 reportRSRP;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportSFTD_NR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportSFTD_NR;
extern asn_SEQUENCE_specifics_t asn_SPC_ReportSFTD_NR_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportSFTD_NR_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ReportSFTD_NR_H_ */
#include <skeletons/asn_internal.h>
