/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_RRCReconfigurationComplete_H_
#define	_RRCReconfigurationComplete_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_CHOICE.h>
#include <skeletons/constr_SEQUENCE.h>

#include "RRC-TransactionIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCReconfigurationComplete__criticalExtensions_PR {
	RRCReconfigurationComplete__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCReconfigurationComplete__criticalExtensions_PR_rrcReconfigurationComplete,
	RRCReconfigurationComplete__criticalExtensions_PR_criticalExtensionsFuture
} RRCReconfigurationComplete__criticalExtensions_PR;

/* Forward declarations */
struct RRCReconfigurationComplete_IEs;

/* RRCReconfigurationComplete */
typedef struct RRCReconfigurationComplete {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct RRCReconfigurationComplete__criticalExtensions {
		RRCReconfigurationComplete__criticalExtensions_PR present;
		union RRCReconfigurationComplete__criticalExtensions_u {
			struct RRCReconfigurationComplete_IEs	*rrcReconfigurationComplete;
			struct RRCReconfigurationComplete__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCReconfigurationComplete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCReconfigurationComplete;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCReconfigurationComplete_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCReconfigurationComplete_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCReconfigurationComplete-IEs.h"

#endif	/* _RRCReconfigurationComplete_H_ */
#include <skeletons/asn_internal.h>
