/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_RRCRelease_H_
#define	_RRCRelease_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_CHOICE.h>
#include <skeletons/constr_SEQUENCE.h>

#include "RRC-TransactionIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCRelease__criticalExtensions_PR {
	RRCRelease__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCRelease__criticalExtensions_PR_rrcRelease,
	RRCRelease__criticalExtensions_PR_criticalExtensionsFuture
} RRCRelease__criticalExtensions_PR;

/* Forward declarations */
struct RRCRelease_IEs;

/* RRCRelease */
typedef struct RRCRelease {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct RRCRelease__criticalExtensions {
		RRCRelease__criticalExtensions_PR present;
		union RRCRelease__criticalExtensions_u {
			struct RRCRelease_IEs	*rrcRelease;
			struct RRCRelease__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCRelease_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCRelease;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCRelease_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCRelease_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCRelease-IEs.h"

#endif	/* _RRCRelease_H_ */
#include <skeletons/asn_internal.h>
