/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_RRCSetup_H_
#define	_RRCSetup_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_CHOICE.h>
#include <skeletons/constr_SEQUENCE.h>

#include "RRC-TransactionIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCSetup__criticalExtensions_PR {
	RRCSetup__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCSetup__criticalExtensions_PR_rrcSetup,
	RRCSetup__criticalExtensions_PR_criticalExtensionsFuture
} RRCSetup__criticalExtensions_PR;

/* Forward declarations */
struct RRCSetup_IEs;

/* RRCSetup */
typedef struct RRCSetup {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct RRCSetup__criticalExtensions {
		RRCSetup__criticalExtensions_PR present;
		union RRCSetup__criticalExtensions_u {
			struct RRCSetup_IEs	*rrcSetup;
			struct RRCSetup__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCSetup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCSetup;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCSetup_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCSetup_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCSetup-IEs.h"

#endif	/* _RRCSetup_H_ */
#include <skeletons/asn_internal.h>
