/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_SCGFailureInformation_IEs_H_
#define	_SCGFailureInformation_IEs_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FailureReportSCG;

/* SCGFailureInformation-IEs */
typedef struct SCGFailureInformation_IEs {
	struct FailureReportSCG	*failureReportSCG;	/* OPTIONAL */
	struct SCGFailureInformation_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCGFailureInformation_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCGFailureInformation_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SCGFailureInformation_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_SCGFailureInformation_IEs_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FailureReportSCG.h"

#endif	/* _SCGFailureInformation_IEs_H_ */
#include <skeletons/asn_internal.h>
