/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_SCGFailureInformationEUTRA_H_
#define	_SCGFailureInformationEUTRA_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_CHOICE.h>
#include <skeletons/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SCGFailureInformationEUTRA__criticalExtensions_PR {
	SCGFailureInformationEUTRA__criticalExtensions_PR_NOTHING,	/* No components present */
	SCGFailureInformationEUTRA__criticalExtensions_PR_scgFailureInformationEUTRA,
	SCGFailureInformationEUTRA__criticalExtensions_PR_criticalExtensionsFuture
} SCGFailureInformationEUTRA__criticalExtensions_PR;

/* Forward declarations */
struct SCGFailureInformationEUTRA_IEs;

/* SCGFailureInformationEUTRA */
typedef struct SCGFailureInformationEUTRA {
	struct SCGFailureInformationEUTRA__criticalExtensions {
		SCGFailureInformationEUTRA__criticalExtensions_PR present;
		union SCGFailureInformationEUTRA__criticalExtensions_u {
			struct SCGFailureInformationEUTRA_IEs	*scgFailureInformationEUTRA;
			struct SCGFailureInformationEUTRA__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCGFailureInformationEUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCGFailureInformationEUTRA;
extern asn_SEQUENCE_specifics_t asn_SPC_SCGFailureInformationEUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_SCGFailureInformationEUTRA_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SCGFailureInformationEUTRA-IEs.h"

#endif	/* _SCGFailureInformationEUTRA_H_ */
#include <skeletons/asn_internal.h>
