/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -fcompound-names -findirect-choice -gen-PER -pdu=all -no-gen-example -no-gen-OER -fincludes-quoted -funnamed-unions -D nr-rrc-f60`
 */

#ifndef	_ServCellIndex_H_
#define	_ServCellIndex_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ServCellIndex */
typedef long	 ServCellIndex_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ServCellIndex_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ServCellIndex;
asn_struct_free_f ServCellIndex_free;
asn_struct_print_f ServCellIndex_print;
asn_constr_check_f ServCellIndex_constraint;
ber_type_decoder_f ServCellIndex_decode_ber;
der_type_encoder_f ServCellIndex_encode_der;
xer_type_decoder_f ServCellIndex_decode_xer;
xer_type_encoder_f ServCellIndex_encode_xer;
per_type_decoder_f ServCellIndex_decode_uper;
per_type_encoder_f ServCellIndex_encode_uper;
per_type_decoder_f ServCellIndex_decode_aper;
per_type_encoder_f ServCellIndex_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServCellIndex_H_ */
#include "asn_internal.h"
