/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_SIB5_H_
#define	_SIB5_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/OCTET_STRING.h>
#include <skeletons/constr_SEQUENCE.h>

#include "T-Reselection.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CarrierFreqListEUTRA;
struct SpeedStateScaleFactors;

/* SIB5 */
typedef struct SIB5 {
	struct CarrierFreqListEUTRA	*carrierFreqListEUTRA;	/* OPTIONAL */
	T_Reselection_t	 t_ReselectionEUTRA;
	struct SpeedStateScaleFactors	*t_ReselectionEUTRA_SF;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIB5;
extern asn_SEQUENCE_specifics_t asn_SPC_SIB5_specs_1;
extern asn_TYPE_member_t asn_MBR_SIB5_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CarrierFreqListEUTRA.h"
#include "SpeedStateScaleFactors.h"

#endif	/* _SIB5_H_ */
#include <skeletons/asn_internal.h>
