/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_UE_NR_Capability_H_
#define	_UE_NR_Capability_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/OCTET_STRING.h>
#include <skeletons/asn_SEQUENCE_OF.h>
#include <skeletons/constr_SEQUENCE.h>
#include <skeletons/constr_SEQUENCE_OF.h>

#include "AccessStratumRelease.h"
#include "PDCP-Parameters.h"
#include "Phy-Parameters.h"
#include "RF-Parameters.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RLC_Parameters;
struct MAC_Parameters;
struct MeasAndMobParameters;
struct UE_NR_CapabilityAddXDD_Mode;
struct UE_NR_CapabilityAddFRX_Mode;
struct FeatureSets;
struct UE_NR_Capability_v1530;
struct FeatureSetCombination;

/* UE-NR-Capability */
typedef struct UE_NR_Capability {
	AccessStratumRelease_t	 accessStratumRelease;
	PDCP_Parameters_t	 pdcp_Parameters;
	struct RLC_Parameters	*rlc_Parameters;	/* OPTIONAL */
	struct MAC_Parameters	*mac_Parameters;	/* OPTIONAL */
	Phy_Parameters_t	 phy_Parameters;
	RF_Parameters_t	 rf_Parameters;
	struct MeasAndMobParameters	*measAndMobParameters;	/* OPTIONAL */
	struct UE_NR_CapabilityAddXDD_Mode	*fdd_Add_UE_NR_Capabilities;	/* OPTIONAL */
	struct UE_NR_CapabilityAddXDD_Mode	*tdd_Add_UE_NR_Capabilities;	/* OPTIONAL */
	struct UE_NR_CapabilityAddFRX_Mode	*fr1_Add_UE_NR_Capabilities;	/* OPTIONAL */
	struct UE_NR_CapabilityAddFRX_Mode	*fr2_Add_UE_NR_Capabilities;	/* OPTIONAL */
	struct FeatureSets	*featureSets;	/* OPTIONAL */
	struct UE_NR_Capability__featureSetCombinations {
		A_SEQUENCE_OF(struct FeatureSetCombination) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *featureSetCombinations;
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct UE_NR_Capability_v1530	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_NR_Capability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_NR_Capability;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RLC-Parameters.h"
#include "MAC-Parameters.h"
#include "MeasAndMobParameters.h"
#include "UE-NR-CapabilityAddXDD-Mode.h"
#include "UE-NR-CapabilityAddFRX-Mode.h"
#include "FeatureSets.h"
#include "UE-NR-Capability-v1530.h"
#include "FeatureSetCombination.h"

#endif	/* _UE_NR_Capability_H_ */
#include <skeletons/asn_internal.h>
