/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -fcompound-names -findirect-choice -gen-PER -pdu=all -no-gen-example -no-gen-OER -fincludes-quoted -funnamed-unions -D nr-rrc-f60`
 */

#ifndef	_UECapabilityEnquiry_v1560_IEs_H_
#define	_UECapabilityEnquiry_v1560_IEs_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_CapabilityRequestFilterCommon;

/* UECapabilityEnquiry-v1560-IEs */
typedef struct UECapabilityEnquiry_v1560_IEs {
	struct UE_CapabilityRequestFilterCommon	*capabilityRequestFilterCommon;	/* OPTIONAL */
	struct UECapabilityEnquiry_v1560_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UECapabilityEnquiry_v1560_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UECapabilityEnquiry_v1560_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UE-CapabilityRequestFilterCommon.h"

#endif	/* _UECapabilityEnquiry_v1560_IEs_H_ */
#include "asn_internal.h"
