/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_ULInformationTransfer_H_
#define	_ULInformationTransfer_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/constr_CHOICE.h>
#include <skeletons/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ULInformationTransfer__criticalExtensions_PR {
	ULInformationTransfer__criticalExtensions_PR_NOTHING,	/* No components present */
	ULInformationTransfer__criticalExtensions_PR_ulInformationTransfer,
	ULInformationTransfer__criticalExtensions_PR_criticalExtensionsFuture
} ULInformationTransfer__criticalExtensions_PR;

/* Forward declarations */
struct ULInformationTransfer_IEs;

/* ULInformationTransfer */
typedef struct ULInformationTransfer {
	struct ULInformationTransfer__criticalExtensions {
		ULInformationTransfer__criticalExtensions_PR present;
		union ULInformationTransfer__criticalExtensions_u {
			struct ULInformationTransfer_IEs	*ulInformationTransfer;
			struct ULInformationTransfer__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ULInformationTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ULInformationTransfer;
extern asn_SEQUENCE_specifics_t asn_SPC_ULInformationTransfer_specs_1;
extern asn_TYPE_member_t asn_MBR_ULInformationTransfer_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ULInformationTransfer-IEs.h"

#endif	/* _ULInformationTransfer_H_ */
#include <skeletons/asn_internal.h>
