/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "38331-f60.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -findirect-choice -gen-PER -pdu=all -D nr-rrc`
 */

#ifndef	_VarPendingRNA_Update_H_
#define	_VarPendingRNA_Update_H_


#include <skeletons/asn_application.h>

/* Including external dependencies */
#include <skeletons/BOOLEAN.h>
#include <skeletons/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VarPendingRNA-Update */
typedef struct VarPendingRNA_Update {
	BOOLEAN_t	*pendingRNA_Update;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarPendingRNA_Update_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarPendingRNA_Update;

#ifdef __cplusplus
}
#endif

#endif	/* _VarPendingRNA_Update_H_ */
#include <skeletons/asn_internal.h>
