#!/usr/bin/env bash

rm -rf nr-rrc-f60 && mkdir nr-rrc-f60

/usr/local/bin/asn1c    -fcompound-names \
    -findirect-choice \
    -gen-PER \
    -pdu=all \
    -no-gen-example \
    -no-gen-OER \
    -fincludes-quoted \
    -funnamed-unions \
    -D nr-rrc-f60 38331-f60.asn

#/usr/local/bin/asn1c    -fcompound-names \
#    -findirect-choice \
#    -gen-PER \
#    -pdu=all \
#    -no-gen-OER \
    # -no-gen-example \
    # -fincludes-quoted \
    # -funnamed-unions \
    # -D nr-rrc-f60 38331-f60.asn
